# Docker
# Build and push an image to Azure Container Registry

trigger:
- main

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: '03b7b0f5-01f4-4849-b4c9-7d7ef9b82650'
  imageRepository: 'yashgautamcodealphaazurecicd'
  containerRegistry: 'codealphacontainer01.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

pool:
  name: 'CodeAlpha-SelfHosted'

stages:
- stage: Build
  displayName: Build and push stage

  jobs:
  - job: Build
    displayName: Build

    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)